# Generated by Django 5.2 on 2025-05-14 14:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='rationitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
