# Generated by Django 5.2 on 2025-05-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0003_rationitem_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='aadhar_number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
