# Generated by Django 5.2 on 2025-05-20 06:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0005_alter_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
