# Generated by Django 5.2 on 2025-05-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0007_alter_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rationitem',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
