# Generated by Django 5.2 on 2025-05-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0008_alter_rationitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rationitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='rationitem',
            unique_together={('name', 'area')},
        ),
    ]
