# Generated by Django 5.2 on 2025-05-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0009_alter_rationitem_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rationitem',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='rationitem',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
