# Generated by Django 5.2 on 2025-05-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0010_alter_rationitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rationitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
