# Generated by Django 5.2 on 2025-05-20 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0011_alter_rationitem_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rationitem',
            unique_together={('name', 'area')},
        ),
    ]
