# Generated by Django 5.2 on 2025-05-20 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0012_alter_rationitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rationitem',
            unique_together=set(),
        ),
    ]
