# Generated by Django 5.2 on 2025-05-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0013_alter_rationitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rationitem',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
