# Generated by Django 5.2 on 2025-05-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0016_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dismissed_by',
            field=models.ManyToManyField(blank=True, related_name='dismissed_notifications', to='ration.familymember'),
        ),
    ]
