# Generated by Django 5.2 on 2025-05-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0017_notification_dismissed_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='dismissed_by',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='seen_by',
        ),
        migrations.AddField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
