# Generated by Django 5.2 on 2025-05-27 17:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ration', '0018_remove_notification_dismissed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dismissed_areas',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
